### PR TITLE
communication: Document how to run meetings

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
This change is mostly a carbon copy of how most meetings were run at
GitLab. What I think is great about most of these points:
- It allows everyone to have a voice
- Highly focussed meetings on what's the agenda
- Great documentation for non-participants after the meeting

All things considered it might be bit of work to get used to, but worth
the initial pain.

### CODE REVIEW

**Comment by sammachin** [comment]
what sort of level would we have for the Adgenda, for example the regular monday meetings would it just be acceptable for each person to have something like:
Sam Machin - Plans for this week, then fill in the details of whats planned during the call?

**Comment by ZJvandeWeg** [comment]
@sammachin Yeah, that would certainly work. Though it would probably be more along:

```
Nick: Plans for the week
```

And after the call it would be more like:
```
Nick: Plans for the week
  Sam: Focussing on A, B
```

Reporting what has been done could be listed with links to PRs and such. The item can be handled in the meeting by just calling out the 1 or 2 of them. This allows everyone to async prepare or catch up too.

**Comment by hardillb** [comment]
Looks like a good starting point to me, we can always adjust if needed after giving it a try.

**Comment by knolleary** [comment]
Looks good to me.

We may want some words on where meeting agendas/notes are kept, to help keep things organised. I know Google Calendar will dynamically created meeting docs if you ask it to - and recurring meetings should reuse the existing doc.

**Comment by ZJvandeWeg** [comment]
> I know Google Calendar will dynamically created meeting docs if you ask it to - and recurring meetings should reuse the existing doc.

@knolleary How does it do this? I was unaware of this feature and would be great to leverage and document along the changes proposed indeed. Google'd a bit, but couldn't find anything.

**Comment by knolleary** [comment]
It is maybe a bit more manual than automatic - but it is one-click to add it:
image

After clicking:

image


But not sure *where* that doc ends up... will experiment a bit.

**Comment by ZJvandeWeg** [comment]
@knolleary Could we merge as is, and iterate in future commits/PRs?

**Pull request merged**
